[build]
  command = "pnpm install && pnpm --filter @domascan/web build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"
  # Frontend code will call /api/*; Netlify redirect below proxies to Koyeb backend
  VITE_API_URL = "/api"

# Redirect all SPA routes to index.html
[[redirects]]
  from = "/api/*"
  to = "https://orthodox-kiley-bahadorgh-a9181840.koyeb.app/:splat"  # Proxy API calls to Koyeb backend
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
