[build]
  command = "pnpm install && pnpm --filter @domascan/web build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://domascan-backend.fly.dev" # Replace with your Fly backend URL

# Redirect all SPA routes to index.html
[[redirects]]
  from = "/api/*"
  to = "https://domascan-backend.fly.dev/:splat"  # Proxy API calls during production
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
